In [1]:
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [20]:
lst1=[1,3,4,5,2]
lst2=[2,5,6,1,2]

arr1=np.array(lst1)
arr2=np.array(lst2)

conc=np.concatenate((arr1,arr2),axis=0)
print('Concatenated list is ',conc)
sort1=np.sort(arr1)
sort2=np.sort(arr2)
print('Sorted list is :',sort1,sort2)

Concatenated list is  [1 3 4 5 2 2 5 6 1 2]
Sorted list is : [1 2 3 4 5] [1 2 2 5 6]


In [27]:
a = np.arange(16).reshape((4, 4))
print(a)
print('Dimensions of array a is ',a.ndim,'D array')
print('Size of array a is ',a.size,'Elements')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Dimensions of array a is  2 D array
Size of array a is  16 Elements


In [45]:
import numpy as np
a=np.array([1,2,3,4,5])
a1=np.expand_dims(a, axis=1)
print('Dimensions of array a is ',a.ndim,'D array')
print('Dimensions of array a1 is ',a1.ndim,'D array')

Dimensions of array a is  1 D array
Dimensions of array a1 is  2 D array


In [50]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 5 5 4 3 2 1]
[[1 2 3 4 5]
 [5 4 3 2 1]]


In [59]:
import numpy as np
a = np.array( [1,2,3,2,1,2,3,2,3,2,1] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print('Unique elements',unique_elements)
print('Count of Unique elements',counts_elements)
# print(np.asarray((unique_elements, counts_elements)))

Original array:
[1 2 3 2 1 2 3 2 3 2 1]
Unique elements [1 2 3]
Count of Unique elements [3 5 3]
